api_version = "unstable"

[[extensions]]
name = "MyTestPayExt"
type = "payments_extension"
handle = "mytestpayext"
payment_session_url = "https://shopify-payments-app-sample.onrender.com/payment"
refund_session_url = "https://shopify-payments-app-sample.onrender.com/refund"
capture_session_url = "https://shopify-payments-app-sample.onrender.com/capture"
void_session_url = "https://shopify-payments-app-sample.onrender.com/void"
merchant_label = "MyTestPay - Admin"
default_buyer_label = "MyTestPay - Buyer"
supported_countries = [
  "AF",
  "AZ",
  "BH",
  "BD",
  "BT",
  "BN",
  "KH",
  "CN",
  "CX",
  "CC",
  "HK",
  "IN",
  "ID",
  "IQ",
  "IL",
  "JP",
  "JO",
  "KZ",
  "KW",
  "KG",
  "LA",
  "LB",
  "MO",
  "MY",
  "MV",
  "MN",
  "MM",
  "NP",
  "OM",
  "PK",
  "PS",
  "PH",
  "QA",
  "RU",
  "SA",
  "SG",
  "KR",
  "LK",
  "TW",
  "TJ",
  "TH",
  "TM",
  "AE",
  "UZ",
  "VN",
  "YE",
  "CA",
  "MX",
  "US",
  "AX",
  "AL",
  "AD",
  "AM",
  "AT",
  "BY",
  "BE",
  "BA",
  "BG",
  "HR",
  "CY",
  "CZ",
  "DK",
  "EE",
  "FO",
  "FI",
  "FR",
  "GE",
  "DE",
  "GI",
  "GR",
  "GL",
  "GP",
  "GG",
  "VA",
  "HU",
  "IS",
  "IE",
  "IM",
  "IT",
  "JE",
  "XK",
  "LV",
  "LI",
  "LT",
  "LU",
  "MT",
  "YT",
  "MD",
  "MC",
  "ME",
  "NL",
  "MK",
  "NO",
  "PL",
  "PT",
  "RE",
  "RO",
  "SM",
  "RS",
  "SK",
  "SI",
  "ES",
  "SJ",
  "SE",
  "CH",
  "TR",
  "UA",
  "GB"
]
supported_payment_methods = [ "visa", "master", "jcb", "american_express" ]
test_mode_available = true
supports_3ds = false
supports_deferred_payments = false
supports_installments = false
multiple_capture = false

  [[extensions.targeting]]
  target = "payments.offsite.render"
